# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sterowaniePokoi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensorId',
            field=models.CharField(max_length=30),
        ),
    ]
