# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sterowaniePokoi', '0002_auto_20161112_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startHour', models.IntegerField()),
                ('endHour', models.IntegerField()),
                ('temp', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sterowaniePokoi.Sensor')),
            ],
        ),
    ]
