# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sterowaniePokoi', '0003_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='setTem',
            field=models.IntegerField(default=19),
        ),
    ]
