# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sterowaniePokoi', '0004_sensor_settem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='setTem',
            new_name='setTemp',
        ),
    ]
