# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sterowaniePokoi', '0005_auto_20161112_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='Nieznany opis', max_length=40),
        ),
    ]
