# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sterowaniePokoi', '0007_sensor_outpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='tolerance',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='setTemp',
            field=models.FloatField(default=19),
        ),
    ]
